### ISSUE TITLE
Create functions for packing / unpacking columns to arrays

### ISSUE THREAD

**Issue by behrica** [scicloj/tablecloth#82]
as follow-up of #78 , so we can close it.

I thought about names like:

columns->array
array->columns

and they should only handle this special case as described in #78.

If this is OK, I do a pR

**Comment by genmeblog** [comment]
Sounds good. Thanks!

Question where to put them. Either `tablecloth.api.join-separate` or maybe in `tablecloth.api.dataset`?.

Anyway, some guidence:
- when you implement both function, ensure they will work on grouped dataset, like for exemaple here: https://github.com/scicloj/tablecloth/blob/master/src/tablecloth/api/join_separate.clj#L44 or https://github.com/scicloj/tablecloth/blob/master/src/tablecloth/api/fold_unroll.clj#L42
- expose functions in `tablecloth.api.api-template`
- evaluate `tablecloth.api.api-template` and call https://github.com/scicloj/tablecloth/blob/master/src/tablecloth/api/api_template.clj#L171 to generate `tablecloth.api`.
- it would be great to create some test (midje)
- it would be great to add examples to https://github.com/scicloj/tablecloth/blob/master/docs/index.Rmd (I will generate html, since it requires some prior setup)
